<a href="https://colab.research.google.com/github/sebaspatric/curso-no-parametrica/blob/main/2.%20Distribuciones%20y%20varianzas%20de%20grupos/2.5%20Homogeneidad%20de%20varianzas%20en%20Python/2_5_Homogeneidad_varianzas_grupos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import levene

# Los datos representan los salarios de 3 departamentos: Ventas, Gerente y Administrador.

# 2 grupos

In [3]:
link = "https://raw.githubusercontent.com/sebaspatric/curso-no-parametrica/refs/heads/main/2.%20Distribuciones%20y%20varianzas%20de%20grupos/2.5%20Homogeneidad%20de%20varianzas%20en%20Python/homogeneidad2grupos.csv"

In [4]:
df = pd.read_csv(link)

In [5]:
#df=pd.read_csv('/content/homogeneidad2grupos.csv')

In [6]:
df.head()

    salary  position
0  57727.0       2.0
1  39907.0       1.0
2  46659.0       2.0
3  40233.0       1.0
4  42198.0       1.0

In [7]:
group1=df[df.position==1.0]
group2=df[df.position==2.0]
group1.head()

    salary  position
1  39907.0       1.0
3  40233.0       1.0
4  42198.0       1.0
6  40324.0       1.0
8  36792.0       1.0

In [8]:
a = group1.salary
b = group2.salary
stat_mean, p_mean = levene(a, b, center='mean')
stat_med, p_med = levene(a, b, center='median')
print('p-value with mean:',p_mean)
print('p-value with median:',p_med)

p-value with mean: 0.0033604796159699404
p-value with median: 0.0034542567782278265

# 3 grupos

In [9]:
link3="https://raw.githubusercontent.com/sebaspatric/curso-no-parametrica/refs/heads/main/2.%20Distribuciones%20y%20varianzas%20de%20grupos/2.5%20Homogeneidad%20de%20varianzas%20en%20Python/homogeneidad3grupos.csv"

In [10]:
#df=pd.read_csv('/content/homogeneidad3grupos.csv')

In [11]:
df = pd.read_csv(link3)

In [12]:
df

      salary  position
0    57727.0       2.0
1    39907.0       1.0
2    46659.0       2.0
3    40233.0       1.0
4    42198.0       1.0
5    69102.0       2.0
6    40324.0       1.0
7    74456.0       2.0
8    36792.0       1.0
9    41007.0       1.0
10  105679.0       2.0
11   85530.0       2.0
12   26312.0       1.0
13   39672.0       2.0
14   69279.0       2.0
15   30221.0       1.0
16   34674.0       1.0
17   39197.0       2.0
18   52404.0       2.0
19   39137.0       1.0
20   74456.0       3.0
21  105679.0       3.0
22   85530.0       3.0
23   39672.0       3.0
24   69279.0       3.0
25   39197.0       3.0
26   52404.0       3.0

In [13]:
group1=df[df.position==1.0]
group2=df[df.position==2.0]
group3=df[df.position==3.0]
a = group1.salary
b = group2.salary
c = group3.salary
stat_mean, p_mean = levene(a, b, c, center='mean')
stat_med, p_med = levene(a, b, c, center='median')
print('p-value with mean:',p_mean)
print('p-value with median:',p_med)

p-value with mean: 0.004882383651530196
p-value with median: 0.006722834715489565

Se rechaza la hipótesis nula, no podemos asumir igualdad de varianzas